[package]
name = "bookPatcher"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "main"
